spring:
    datasource:
        url: jdbc:mysql://localhost:3306/toss_db?serverTimezone=Asia/Seoul
        username: toss
        password: point
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6